config/routes.rb
Rails.application.routes.draw do

  root "hello#index"
  get "/logout",  to: "sessions#destroy"
  delete "/logout",  to: "sessions#destroy"
  get    "/login",   to: "sessions#new" ,as: 'login_fault'
  get    "/users/new",   to: "users#new" ,as: 'new_user'
  get    "/users/show",   to: "users#show" ,as: 'user_page'
  post   "/login",   to: "sessions#create"
  delete '/items/:id' , to: 'items#destroy' ,as: 'items_delete'
  post '/items/:id/items_create' , to: 'items#create' ,as: 'items_create_item'
  patch '/items/:id/items_update', to: 'items#update', as: 'items_update'
  post '/items/skill_edit' ,to: 'items#skill_edit',as: 'skill_edit'






  # get '/items/:id' , to: 'items#skill_edit' ,as: 'after_delete'
  get '/items/skill_edit' ,to: 'items#skill_edit',as: 'skill_edit_user'
  get '/items/add_items/:id', to: 'items#add_items', as: 'add_items'

  resources :users, controller: 'users'

  resources :items, only: [:new, :create, :destroy, :update] do
    member do
      get 'items_delete'
      get 'items_update' 
      get 'items_create'
      post 'update_selected_day' 
    end
  end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/views/hello/index.html.erb
<%= render 'layouts/header' %>
  <div class="login">
  <h1 class ="login-title">ログイン</h1>
    <div class="login_form">
      <%= form_with(url: login_path, scope: :session) do |f| %>

        <div class="form_box ">
        <div class="form_label">
          <label>メールアドレス</label><br>
        </div>
        <%= f.email_field :email, class: 'form-underline' %>
      </div>

      <div class="form_box">
        <div class="form_label">
          <label>パスワード</label><br>
        </div>
        <%= f.password_field :password,  class: 'form-underline' %>
      </div>

      <div class="form_box">
        <%= f.submit "ログインする", class: "login_submit_button" %>
      </div>

      <div class="form_box">
      <%= link_to "新規登録する", '/users/new', class: "button_blue blue_button_font" %>
      </div>
      <% end %>
    </div>

  </div>
<%= render 'layouts/footer' %>