config/routes.rb
Rails.application.routes.draw do

  root "hello#index"
  get "/logout",  to: "sessions#destroy"
  delete "/logout",  to: "sessions#destroy"
  get    "/login",   to: "sessions#new" ,as: 'login_fault'
  get    "/users/new",   to: "users#new" ,as: 'new_user'
  get    "/users/show",   to: "users#show" ,as: 'user_page'
  post   "/login",   to: "sessions#create"
  delete '/items/:id' , to: 'items#destroy' ,as: 'items_delete'
  post '/items/:id/items_create' , to: 'items#create' ,as: 'items_create_item'
  patch '/items/:id/items_update', to: 'items#update', as: 'items_update'
  post '/items/skill_edit' ,to: 'items#skill_edit',as: 'skill_edit'






  # get '/items/:id' , to: 'items#skill_edit' ,as: 'after_delete'
  get '/items/skill_edit' ,to: 'items#skill_edit',as: 'skill_edit_user'
  get '/items/add_items/:id', to: 'items#add_items', as: 'add_items'

  resources :users, controller: 'users'

  resources :items, only: [:new, :create, :destroy, :update] do
    member do
      get 'items_delete'
      get 'items_update' 
      get 'items_create'
      post 'update_selected_day' 
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :item, foreign_key: 'user_id'
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }, allow_nil: true
  has_one_attached :avatar


  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # 永続化セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    remember_digest
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update] # ログイン済みユーザーのみアクセス可能なアクションを指定
  before_action :correct_user, only: [:edit, :update] # 正しいユーザーのみアクセス可能なアクションを指定

  def show
    # @user = User.find(params[:id])
    @user = User.find_by(id: session[:user_id])
    @id = session[:user_id]

    @today =Date.today
    @last_month_day =Date.today.last_month
    @two_months_ago_day =Date.today.months_since(-2)

    # @item = item.find(params[user_id: user_id])
    @buckend_thismonth_sum = Item.where(user_id: @id, categories_id: 1,created_at: @today.in_time_zone.all_month).sum(:learning_time)
    @buckend_lastmonth_sum = Item.where(user_id: @id, categories_id: 1,created_at: @last_month_day.in_time_zone.all_month).sum(:learning_time)
    @buckend_two_months_ago_sum = Item.where(user_id: @id, categories_id: 1,created_at:  @two_months_ago_day.in_time_zone.all_month).sum(:learning_time)

    @frontend_thismonth_sum = Item.where(user_id: @id, categories_id: 2,created_at: @today.in_time_zone.all_month).sum(:learning_time)
    @frontend_lastmonth_sum = Item.where(user_id: @id, categories_id: 2,created_at: @last_month_day.in_time_zone.all_month).sum(:learning_time)
    @frontend_two_months_ago_sum = Item.where(user_id: @id, categories_id: 2,created_at:  @two_months_ago_day .in_time_zone.all_month).sum(:learning_time)

    @infra_thismonth_sum = Item.where(user_id: @id, categories_id: 3,created_at: @today.in_time_zone.all_month).sum(:learning_time)
    @infra_lastmonth_sum = Item.where(user_id: @id, categories_id: 3,created_at: @last_month_day.in_time_zone.all_month).sum(:learning_time)
    @infra_two_months_ago_sum = Item.where(user_id: @id, categories_id: 3,created_at:  @two_months_ago_day .in_time_zone.all_month).sum(:learning_time)

    # categories_id: 1,created_at:  @selected_day.in_time_zone.all_month
    # created_at:  @selected_day.in_time_zone.all_month)

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to root_url
    else

      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :introduction,:avatar,:password_confirmation)
    end


    # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url, status: :forbidden
      end
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url, status: :see_other) unless @user == current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% content_for :js do %>

  <%= javascript_import_module_tag 'input_rule' %>

<% end %>

<%= render 'layouts/header' %>

<div class="edit-flame">
  <h1>自己紹介を編集する</h1>
  <%= form_with(model: @user) do |f| %>
  <div class="edit-box">
    <div class="edit-self-introduction">
      <label>自己紹介文</label>
      <%= f.text_area :introduction, class: 'edit-self-introduction-form', id:'user_introduction' %>
      <label>50文字以上、200文字未満で入力してください。</label>
    </div>
    <div class="add-img-box">
      <label>アバター画像</label>
      <div class="custom-file-input">
        <button><%= f.label '画像ファイルを添付する', class: 'custom-file-label' %></button>
        <%= f.file_field :avatar, class: 'custom-file-input', accept: 'image/*' %>
      </div>
    </div>
    <div class="edit-confirm">
    <%= f.submit "自己紹介を確定する", class: "edit-confirm-button" , id:'updateButton' %>
    </div>
  </div>
  <% end %>
</div>
<%= render 'layouts/footer' %>

app/views/users/new.html.erb
<%= render 'layouts/header' %>

<div class="login">

  <h1 class ="login-title">新規登録</h1>

  <div class="row">
    <div class="login_form">
      <%= form_with(model: @user) do |f| %>
        <%= render 'shared/error_messages' %>

      <div class="form_box ">
        <div class="form_label">
          <label>氏名</label><br>
        </div>
        <%= f.text_field :name, class: 'form-underline' %>
      </div>

      <div class="form_box">
        <div class="form_label">
          <label>メールアドレス</label><br>
        </div>
        <%= f.email_field :email, class: 'form-underline ' %>
      </div>

      <div class="form_box">
        <div class="form_label">
          <label>パスワード</label><br>
        </div>
        <%= f.password_field :password,  class: 'form-underline ' %>
      </div>

      <div class="form_box">
        <%= f.submit "登録する", class: "login_submit_button" %>
      </div>
      
      <% end %>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/users/show.html.erb
<%= render 'layouts/header' %>

<div class="user-info">
  <div class="user-info-flame">
    <div class="avataer-name">
      <div class="user-avatar">
        <%= image_tag(@user.avatar , class: "user-avatar") if @user.avatar.present? %>
      </div>
      <div class="user-name"><p><%= @user.name %></p></div>
    </div>
    <div class="user-self-introduction">
      <h1>自己紹介</h1>
        <div class="introduction-container">
          <p><%= @user.introduction %></p>
        </div>
        <%= link_to "自己紹介を編集する", edit_user_path(session[:user_id]) ,class:"user-self-introduction-btn"%>
    </div>
  </div>


  <div class="study-chart-frame">
  <div class="study-chart-box">
    <h1>学習チャート</h1>
  </div>
  <%= link_to "編集する", skill_edit_user_path(id: @id) ,class: "user-self-introduction-btn" %>

<canvas id="myChart"></canvas>

</div>

<%= render 'layouts/footer' %>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
var ctx = document.getElementById('myChart');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ['先々月', '先月', '今月'],
        datasets: [
          {
            label: 'バックエンド',
            data: ['<%= @buckend_two_months_ago_sum %>',
                  '<%= @buckend_lastmonth_sum  %>' ,
                  '<%= @buckend_thismonth_sum %>'],
            backgroundColor: [
                'rgb(243,174,187)'
            ],
        },
        {
            label: 'フロントエンド',
            data: ['<%= @frontend_two_months_ago_sum %>',
                   '<%= @frontend_lastmonth_sum  %>' ,
                   '<%= @frontend_thismonth_sum %>'],
            backgroundColor: [
                'rgb(247,209,170)',
            ]
        },
        {
          label: 'インフラ',
          data: ['<%= @infra_two_months_ago_sum %>',
                 '<%= @infra_lastmonth_sum  %>' ,
                 '<%= @infra_thismonth_sum %>'],
          backgroundColor: [
            'rgb(250,230,181)',
          ]
      }
      ]
    },
    options: {
        scales: {
            y: {
              suggestedMin: 0,
              suggestedMax: 100
            }
        }
    }
});
</script>