config/routes.rb
Rails.application.routes.draw do

  root "hello#index"
  get "/logout",  to: "sessions#destroy"
  delete "/logout",  to: "sessions#destroy"
  get    "/login",   to: "sessions#new" ,as: 'login_fault'
  get    "/users/new",   to: "users#new" ,as: 'new_user'
  get    "/users/show",   to: "users#show" ,as: 'user_page'
  post   "/login",   to: "sessions#create"
  delete '/items/:id' , to: 'items#destroy' ,as: 'items_delete'
  post '/items/:id/items_create' , to: 'items#create' ,as: 'items_create_item'
  patch '/items/:id/items_update', to: 'items#update', as: 'items_update'
  post '/items/skill_edit' ,to: 'items#skill_edit',as: 'skill_edit'






  # get '/items/:id' , to: 'items#skill_edit' ,as: 'after_delete'
  get '/items/skill_edit' ,to: 'items#skill_edit',as: 'skill_edit_user'
  get '/items/add_items/:id', to: 'items#add_items', as: 'add_items'

  resources :users, controller: 'users'

  resources :items, only: [:new, :create, :destroy, :update] do
    member do
      get 'items_delete'
      get 'items_update' 
      get 'items_create'
      post 'update_selected_day' 
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
    self.primary_key = 'id'
    belongs_to :user, foreign_key: 'user_id'

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  

    def new
      @item = Item.new
    end




    
    def update_selected_day
        puts "Reached update_selected_day method"  # この行を追加
        selected_day = params[:selectedDay] # JavaScriptから送られたデータを取得
        selected_id = params[:selectedid] 
        selected_no = params[:selectedno] 
        Rails.logger.debug "Selected Day7: #{selected_day.inspect}"
        Rails.logger.debug "Selected Id7: #{selected_id.inspect}"
        Rails.logger.debug "Selected No7: #{selected_no.inspect}"
      
        user_id = params[:selectedid]
        @item = Item.find_by(id: params[:id])
        @user = User.find(params[:id])
        @no = selected_no
      
        if  selected_day == nil
            @selected_day =   @today
            else 
                @selected_day =  selected_day
            end

        Rails.logger.debug "Selected Day3: #{@selected_day.inspect}"
      
        # すでに初期化されている場合は再初期化しないようにする
        @today ||= Date.today
        @last_month_day ||= Date.today.last_month
        @two_months_ago_day ||= Date.today.months_since(-2)
      
        # 適切なデータを取得する処理をここに追加
        # @item =  Item.where(user_id: @user.id ,created_at:  @selected_day.in_time_zone.all_month)
        # redirect_to skill_edit_user_path(selected_day: selected_day, selected_no:  selected_no)
        respond_to do |format|
            format.json { render json: { selected_day: selected_day, selected_no: selected_no } }
          end
          
      end

    def skill_edit
        


        @user = User.find_by(id: session[:user_id])

        if params[:created_at].present?
            selected_day = params[:created_at]
            selected_no = params[:selected_no] 
        else
         selected_day = params[:selectedDay] # JavaScriptから送られたデータを取得
         selected_no = params[:selectedno] 
        end

        selected_id = params[:selectedid] 
       
        Rails.logger.debug "Selected Day1: #{selected_day.inspect}"
        Rails.logger.debug "Selected Id1: #{selected_id.inspect}"
        Rails.logger.debug "Selected No1: #{selected_no.inspect}"

        @no=selected_no

        Rails.logger.debug "Selected user: #{@user.inspect}"
        Rails.logger.debug "Selected No2: #{@no.inspect}"

        @category = Category.all
        id = params[:id]
        user_id = Item.find_by(user_id: params[:id])

        Rails.logger.debug "params[:id]: #{id.inspect}"
        Rails.logger.debug "params[:user_id]: #{user_id.inspect}"






        #user_id = params[:user_id]
        # @item= Item.find_by(id: params[:id])
        #@user = User.find(params[:id])
        @today =Date.today
        @last_month_day =Date.today.last_month
        @two_months_ago_day =Date.today.months_since(-2)

        # @selected_day = params.fetch(:selected_day, @today)
        if  selected_day == nil
        @selected_day =   @today
        else 
            @selected_day =  selected_day
        end

        @this_month = Date.today.month
        @last_month = Date.today.last_month.month
        @two_months_ago = Date.today.months_since(-2).month

 
        # if User.find_by(id: params[:id])  == nil
        #     user_id = @item.user_id
        #     @user = User.find(user_id)
        #   else
        #     @user = User.find(params[:id])
        # end

    end
    


    
    def add_items
        @user = User.find_by(id: session[:user_id])
        @item = Item.new
        @create = params[:created_at]
        @no = params[:selected_no]
        # @category = Category.find_by!(params[:categories_id])
        @category = Category.find(params[:categories_id])
        user_id = Item.find_by(id: params[:id])
        @user = User.find(params[:id])

    end

    def destroy
        @user = User.find_by(id: session[:user_id])
        @item = Item.find(params[:id])
        @item.destroy

        render json: { deleted_item_id: @item.name }


        # if @item.destroy
        #     item_name = @item.name 
        #     @messege = { 'message' => '削除しました。' }
           
        #     respond_to do |format|      
        #         format.html
        #         format.json { render json: @messege }
        #     end
                
        #     else

        #     messege = "削除失敗"
        #     render json: { messege: messege }
        # end
        # redirect_to skill_edit_user_url, status: :see_other
    end

    def update
        item_id = params[:id]

      
        @item = Item.find(item_id)

      
        if @item.update(item_params)
          render json: { update_item_id: @item }
        else
          render json: { error: '更新に失敗しました' }, status: :unprocessable_entity
        end
      end


  
    def create
        created_at = params[:item][:created_at] # Parametersからcreated_atを取得
        @item = Item.new(create_params.merge(created_at: created_at)) # created_atをmergeして新しいItemオブジェクトを作成

        # Rails.logger.debug "Item found: #{@item.inspect}"
        # debugger

        if @item.save
            # redirect_to skill_edit_user_path(created_at), notice: '追加されました' 
            # debugger
             render json: {add_item_id: @item  }
        else


          render json: { error: "項目の追加に失敗しました" }, status: :unprocessable_entity

        end
        end

    #     @item = Item.new(item_params)

    #     if @item.save
    #     #   render json: { name: @item.name ,learning_time: @item.learning_time,categories_id: @item.categories_id  }
    #       redirect_to skill_edit_user_path, notice: '追加されました' 
    #     else
    #       render json: { error: "項目の追加に失敗しました" }, status: :unprocessable_entity
    #     end
    #   end
  
    private
  
    def item_params
        params.require(:item).permit(:learning_time, :id, :categories_id)    
    end

    def create_params
        params.require(:item).permit(:name, :learning_time, :categories_id,:created_at, :user_id,:id)
    end  
  
  end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/add_items.html.erb
<% content_for :js do %>

  <%= javascript_import_module_tag "add_script" %>

<% end %>


<%= render 'layouts/header' %>




<div class="edit-flame">
  <h1><%=  @category.name %>に項目を追加</h1>


    <%= form_with(model: @item, url: skill_edit_user_path(created_at: @create, selected_no: @no), local: true, html: { id: "add-form" }) do |form| %>


    <div class="edit-box">
      <div class="edit-self-introduction">
        <label>項目名</label>
        <%= form.text_area :name, class: 'add-items-form',id: "itemName"%>
      </div>
      <div class="add-img-box">
        <label>学習時間</label>
        <%= form.number_field :learning_time,class: 'add-items-form', min: 0,id:"itemLearningtime" %>
        <%= form.hidden_field :categories_id, value: @category.id ,id: "categoryid" %>
        <%= form.hidden_field :user_id, value: @user.id ,id: "userId" %>
        <%= form.hidden_field :category_name, value: @category.name ,id: "categoryname" %>
        <%= form.hidden_field :created_at, value: @create  ,id: "createdat" %>
        <label>分単位で入力してください。</label>
      </div>
      <div class="edit-confirm">
        <button id='addButton' add-button-id="<%= @user.id %>"><%= form.submit '追加する', class: "edit-confirm-button create-btn", id:"input-rule" %></button>
      </div>


      <div id='add-modal' class='modal' >
      <div class="modal-content">
      <div id="addItemIdArea"></div> 


  
        <div class="modal-buttons">
          <button class="back-edit-button" id="add-confirm-yes"><%= link_to "編集ページに戻る", skill_edit_user_path(created_at: @create,selected_no: @no)  %></button>
        </div>
      </div>
    </div>
    </div>





  <% end %>


 
</div>
<%= render 'layouts/footer' %>

app/views/items/skill_edit.html.erb
<% content_for :js do %>

  <%= javascript_import_module_tag 'select' %>
  <%= javascript_import_module_tag 'delete_script' %>
  <%= javascript_import_module_tag 'update_script' %>
<% end %>



<%= render 'layouts/header' %>




<div class="skill-edit-main">
  <div class="pull-down-bottun">
  <label class="selectbox-3">
  <%= select_tag 'date_selection', options_for_select([
    [@today.month.to_s + '月', "#{@today},#{@user.id},#{1}", selected: ("1" == @no)],
    [@last_month_day.month.to_s + '月', "#{@last_month_day},#{@user.id},#{2}", selected: ("2" == @no)],
    [@two_months_ago_day.month.to_s + '月', "#{@two_months_ago_day},#{@user.id},#{3}",selected: ("3" == @no)]
  ], selected: "#{@no}") %>
</label>
  </div>

  
 
  <script>

  </script>

  <div class="category-box">
    <div class="category-title">
      <h1><p>バックエンド</p></h1>
      <%= link_to "項目を追加する", add_items_path(@user,categories_id: 1,created_at:  @selected_day,selected_no:@no), class:"add-items-button" %>
    </div>
    
    <table>
      <tr>
        <td>項目名</td>
        <td>学習時間</td>
        <td></td>
        <td></td>
      </tr>

      <% Item.where(categories_id: 1,user_id:@user.id, created_at:  @selected_day.in_time_zone.all_month).each do |p| %>
        <tr>
          <td><%= p.name %></td>

          <%= form_with(model: p, url: skill_edit_user_path(created_at: @selected_day, selected_no: @no), method: :post, id: "update-form") do |form| %>
            <td><%= form.number_field :learning_time, min: 0, value: p.learning_time ,id: "learningTime"  , class: '' %></td>
            <td><button id='updateButton', update-button-id="<%= p.id %>" ><%= form.submit "学習時間を保存する", class: "learning-time-confirm update-btn"  %></button>

            </td>

            <div id="update-modal" class="modal">
            <div class="modal-content">
                <div id="updateItemIdArea"></div> 
                 
                <div class="modal-buttons">
              <button class="back-edit-button" id="update-confirm-yes"><%= link_to "編集ページに戻る",skill_edit_user_path(created_at: @selected_day,selected_no: @no)  %></button>
              </div>
            </div>
          </div>
        </td>
        <% end %>
          <td>
          <button id="deleteButton" class="d-button delete-btn", delete-button-id="<%= p.id %>" >削除する</button>
          
          <div class="modal" id="delete-modal">
          <div class="modal-content">
          <div id="deletedItemIdArea"></div> 

            <div class="modal-buttons">
            <button class="back-edit-button" id="confirm-yes"><%= link_to "編集ページに戻る",skill_edit_user_path(created_at: @selected_day,selected_no: @no) , method: :delete  %></button>
              </div>
            </div>
          </div>
          </td>
        </tr>
      <% end %>
    </table>
  </div>



  <div class="category-box">
    <div class="category-title">
      <h1><p>フロントエンド</p></h1>
      <%= link_to "項目を追加する", add_items_path(@user,categories_id: 2,created_at:  @selected_day,selected_no:@no), class:"add-items-button" %>
    </div>
    
    <table>
      <tr>
        <td>項目名</td>
        <td>学習時間</td>
        <td></td>
        <td></td>
      </tr>

      <% Item.where(categories_id: 2,user_id:@user.id, created_at:  @selected_day.in_time_zone.all_month).each do |p| %>
        <tr>
          <td><%= p.name %></td>

          <%= form_with(model: p, url: skill_edit_user_path(created_at: @selected_day, selected_no: @no), method: :post, id: "update-form") do |form| %>
            <td><%= form.number_field :learning_time, min: 0, value: p.learning_time ,id: "learningTime"  , class: '' %></td>
            <td><button id='updateButton', update-button-id="<%= p.id %>" ><%= form.submit "学習時間を保存する", class: "learning-time-confirm update-btn"  %></button>
            <%= form.hidden_field :item_id, value: p.id, id:'item-id'%>
            </td>

            <div id="update-modal" class="modal">
            <div class="modal-content">
                <div id="updateItemIdArea"></div> 
                 
                <div class="modal-buttons">
              <button class="back-edit-button" id="update-confirm-yes"><%= link_to "編集ページに戻る",skill_edit_user_path(created_at: @selected_day,selected_no: @no)  %></button>
              </div>
            </div>
          </div>
        </td>
        <% end %>
          <td>
          <button id="deleteButton" class="d-button delete-btn", delete-button-id="<%= p.id %>" >削除する</button>
          
          <div class="modal" id="delete-modal">
          <div class="modal-content">
          <div id="deletedItemIdArea"></div> 

            <div class="modal-buttons">
            <button class="back-edit-button" id="confirm-yes"><%= link_to "編集ページに戻る",skill_edit_user_path(created_at: @selected_day,selected_no: @no) , method: :delete  %></button>
              </div>
            </div>
          </div>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="category-box">
  <div class="category-title">
    <h1><p>インフラ</p></h1>
    <%= link_to "項目を追加する", add_items_path(@user,categories_id: 3,created_at:  @selected_day,selected_no:@no), class:"add-items-button" %>

  </div>
  
  <table>
    <tr>
      <td>項目名</td>
      <td>学習時間</td>
      <td></td>
      <td></td>
    </tr>

    <% Item.where(categories_id: 3,user_id:@user.id, created_at:  @selected_day.in_time_zone.all_month).each do |p| %>
      <tr>
        <td><%= p.name %></td>

        <%= form_with(model: p, url: skill_edit_user_path(created_at: @selected_day, selected_no: @no), method: :post, id: "update-form") do |form| %>
          <td><%= form.number_field :learning_time, min: 0, value: p.learning_time ,id: "learningTime"  , class: '' %></td>
          <td><button id='updateButton', update-button-id="<%= p.id %>" ><%= form.submit "学習時間を保存する", class: "learning-time-confirm update-btn"  %></button>
          <%= form.hidden_field :item_id, value: p.id, id:'item-id'%>
          </td>

          <div id="update-modal" class="modal">
          <div class="modal-content">
              <div id="updateItemIdArea"></div> 
               
              <div class="modal-buttons">
            <button class="back-edit-button" id="update-confirm-yes"><%= link_to "編集ページに戻る",skill_edit_user_path(created_at: @selected_day,selected_no: @no)  %></button>
            </div>
          </div>
        </div>
      </td>
      <% end %>
        <td>
        <button id="deleteButton" class="d-button delete-btn", delete-button-id="<%= p.id %>" >削除する</button>
        
        <div class="modal" id="delete-modal">
        <div class="modal-content">
        <div id="deletedItemIdArea"></div> 

          <div class="modal-buttons">
          <button class="back-edit-button" id="confirm-yes"><%= link_to "編集ページに戻る",skill_edit_user_path(created_at: @selected_day,selected_no: @no) , method: :delete  %></button>
            </div>
          </div>
        </div>
        </td>
      </tr>
    <% end %>
  </table>
</div>

  
 

</div>



<%= render 'layouts/footer' %>

<div></div>

app/views/items/update_selected_day.html.erb
<% content_for :js do %>
  <%= javascript_import_module_tag "modal" %>
  <%= javascript_import_module_tag "select" %>
<% end %>

<%= render 'layouts/header' %>

<div class="skill-edit-main">
  <div class="pull-down-bottun">
  <label class="selectbox-3">
  <%= select_tag 'date_selection', options_for_select([
    [@today.month.to_s + '月', "#{@today},#{@user.id},#{1}", selected: (1 == @no)],
    [@last_month_day.month.to_s + '月', "#{@last_month_day},#{@user.id},#{2}", selected: (2 == @no)],
    [@two_months_ago_day.month.to_s + '月', "#{@two_months_ago_day},#{@user.id},#{3}",selected: (3 == @no)]
  ], selected: "#{@no}") %>
</label>
  </div>

  
  <p>選んだ月</p>
  <%= @selected_day %>

  <div class="category-box">
    <div class="category-title">
      <h1><p>バックエンド</p></h1>
      <%= link_to "項目を追加する", add_items_path(@user), class:"add-items-button" %>
    </div>
    
    <table>
      <tr>
        <td>項目名</td>
        <td>学習時間</td>
        <td></td>
        <td></td>
      </tr>

      <% Item.where(categories_id: 1,created_at:  @selected_day.in_time_zone.all_month).each do |p| %>
        <tr>
          <td><%= p.name %><%= p.created_at.strftime("%m月") %></td>

          <%= form_with(model: p, local: true) do |f| %>
            <td><%= f.number_field :learning_time, min: 0, value: p.learning_time, class: '' %></td>
            <td><%= f.submit "学習時間を保存する", class: "learning-time-confirm update-btn" %></td>

            <div id="confirmation-modal-update" class="modal" data-items-update-url="<%= items_update_item_path(p.id) %>">
            <div class="modal-content">
            <p><%= p.name %>の学習時間を保存しました！</p>
              <div class="modal-buttons">
              <button class="back-edit-button" id="confirm-yes"><%= link_to "編集ページに戻る", item_path(p.user_id)  %></button>
              </div>
            </div>
          </div>
        </td>
        <% end %>
          <td>
            <%= link_to '削除する', item_path(p.id), method: :delete, data: { turbo_method: :delete }, class: 'd-button delete-btn' %>
            
            <div id="confirmation-modal" class="modal" data-items-delete-url="<%= items_delete_path %>">
              <div class="modal-content">
              <p><%= p.name %>を削除しました！</p>
                <div class="modal-buttons">
                <button class="back-edit-button" id="confirm-yes"><%= link_to "編集ページに戻る", item_path(p.id), method: :delete, data: { turbo_method: :delete },remote: true  %></button>
                </div>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
    </table>
  </div>


  <div class="category-box">
  <div class="category-title">
    <h1><p>フロントエンド</p></h1>
    <%= link_to "項目を追加する", add_items_path(@user), class:"add-items-button" %>
  </div>
  
  <table>
    <tr>
      <td>項目名</td>
      <td>学習時間</td>
      <td></td>
      <td></td>
    </tr>

    <% Item.where(categories_id: 1).each do |p| %>
      <tr>
        <td><%= p.name %><%= p.id %></td>

        <%= form_with(model: p, local: true) do |f| %>
          <td><%= f.number_field :learning_time, min: 0, value: p.learning_time, class: '' %></td>
          <td><%= f.submit "学習時間を保存する", class: "learning-time-confirm" %></td>
        <% end %>

        <td>
          <%= link_to '削除する', item_path(p.id), method: :delete, data: { turbo_method: :delete }, class: 'd-button delete-btn' %>
          <div id="confirmation-modal" class="modal">
            <div class="modal-content">
              <p><%= p.name %>を削除しました！</p>
              <div class="modal-buttons">
                <button clss="add-items-button" id="confirm-yes"><%= link_to "編集ページに戻る", item_path(p.id), method: :delete, data: { turbo_method: :delete },remote: true  %></button>
              </div>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
</div>

</div>



<%= render 'layouts/footer' %>

<div></div>