config/routes.rb
Rails.application.routes.draw do

  root "hello#index"
  get "/logout",  to: "sessions#destroy"
  delete "/logout",  to: "sessions#destroy"
  get    "/login",   to: "sessions#new" ,as: 'login_fault'
  get    "/users/new",   to: "users#new" ,as: 'new_user'
  get    "/users/show",   to: "users#show" ,as: 'user_page'
  post   "/login",   to: "sessions#create"
  delete '/items/:id' , to: 'items#destroy' ,as: 'items_delete'
  post '/items/:id/items_create' , to: 'items#create' ,as: 'items_create_item'
  patch '/items/:id/items_update', to: 'items#update', as: 'items_update'
  post '/items/skill_edit' ,to: 'items#skill_edit',as: 'skill_edit'






  # get '/items/:id' , to: 'items#skill_edit' ,as: 'after_delete'
  get '/items/skill_edit' ,to: 'items#skill_edit',as: 'skill_edit_user'
  get '/items/add_items/:id', to: 'items#add_items', as: 'add_items'

  resources :users, controller: 'users'

  resources :items, only: [:new, :create, :destroy, :update] do
    member do
      get 'items_delete'
      get 'items_update' 
      get 'items_create'
      post 'update_selected_day' 
    end
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer_logo">
    <p>profile site</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <div class ="logo">
  <%  if  logged_in? %>
  <%= link_to "My profile", user_page_path(session[:user_id]) , class:"logo-font" %>
  <% else %>
    <%= link_to "My profile", root_path , class:"logo-font" %>
  <% end %>
  </div>



  <div class ="logout_button">
  <% if current_page?(root_path)  || current_page?(login_fault_path) %>

  <%  elsif  current_page?(new_user_path)   %>


    <button ><%= link_to "ログイン",  root_path ,method: :get %></button>



  <%  elsif  logged_in? %>
  <button ><%= link_to "ログアウト",  logout_path ,method: :delete %></button>

  <% else %>
  <form class="button_to" method="get" action="/sessions/new">
    <button class="header-button" type="submit">ログイン</button>
  </form>
  <% end %>
</div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sample App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name='csrf-token' content='<%= form_authenticity_token %>' >


    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>


    <%= yield(:js) %>

    
  </head>

  <body>
    <%= yield %>

  </body>
</html>